name: CD_workflow_object_transfer
run-name: zip the repo and store it in a bucket
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  transfer_object_to_object_store:
    if: ${{ github.event.pull_request.merged }} ||  ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "install zip package"
        run: "sudo apt install zip"
      - name: "zip the repository"
        run: |
          zip -r serverless.zip .

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "upload-file"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "./serverless.zip"
          destination: "csye6225-demo-gcf-source/serverless.zip"
